#!/usr/bin/env ruby

require 'optparse'

command = ARGV[0]
name = ARGV[1]
options = {}

OptionParser.new do |opts|
  opts.banner = "Usage: grocerytracker [command] [options]"

  opts.on("--price [PRICE]", "The price") do |price|
    options[:price] = price
  end

  opts.on("--calories [CALORIES]", "The calories") do |calories|
    options[:calories] = calories
  end
end.parse!

if name.nil? or name.empty?
  puts "You must provide the name of the product you are adding."
  exit
end

missing_things = []
missing_things << "price" unless options[:price]
missing_things << "total calories" unless options[:calories]
unless missing_things.empty?
  puts "You must provide the #{missing_things.join(" and ")} of the product you are adding."
  exit
end

puts "Theoretically creating: a purchase named #{name}, with #{options[:calories]} calories and $#{options[:price]} cost"
